// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./src/components/Article.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    Header: typeof import('./src/components/Header.vue')['default']
    Hero: typeof import('./src/components/Hero.vue')['default']
    IconBack: typeof import('./src/components/icons/IconBack.vue')['default']
    IconGithub: typeof import('./src/components/icons/IconGithub.vue')['default']
    IconLink: typeof import('./src/components/icons/IconLink.vue')['default']
    IconLinkedin: typeof import('./src/components/icons/IconLinkedin.vue')['default']
    IconMonospace: typeof import('./src/components/icons/IconMonospace.vue')['default']
    IconTwitter: typeof import('./src/components/icons/IconTwitter.vue')['default']
    IconYoutube: typeof import('./src/components/icons/IconYoutube.vue')['default']
    Info: typeof import('./src/components/Info.vue')['default']
    MetaTags: typeof import('./src/components/MetaTags.vue')['default']
    MoreArticles: typeof import('./src/components/MoreArticles.vue')['default']
    Notice: typeof import('./src/components/Notice.vue')['default']
  }
}

export { }
